name: deploy website

on:
  push:
    branches: [ "main" ]

permissions:
  actions: read
  contents: write
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: yarn
      
      - name: linter
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    needs: [ "test" ]
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: yarn
      
      - name: build website
        run: yarn build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist   